title: Dashboard

layout:
  sections: 4
  width: 2
  sectionPadding: 20
  cardPadding: 10

style:
  background: "#181926"
  sectionBackground: "#24273a"
  cardBackground: "#181926"
  cardHover: "#c6a0f6"
  text: "#cad3f5"
  textHover: "#24273a"
  configaccent: "#c6a0f6"
  statusOnline: "#a6da95"
  statusOffline: "#121212"

linkSections:
  - title: main
    links:
      - title: Proxmox
        url: https://pve.tbrouwer.com
        icon: hl-proxmox
        status: true

      - title: Passbolt
        url: https://passbolt.tbrouwer.com
        icon: hl-passbolt
        status: true

      - title: Grafana
        url: https://grafana.tbrouwer.com
        icon: hl-grafana
        status: true

      - title: Pi-hole
        url: https://pihole.tbrouwer.com
        icon: hl-pi-hole
        status: true

      - title: Pi-hole 2
        url: https://pihole-2.tbrouwer.com
        icon: hl-pi-hole
        status: true

      - title: Wireguard
        url: https://wireguard.tbrouwer.com
        icon: hl-wireguard
        status: true

      - title: Portainer
        url: https://portainer.tbrouwer.com
        icon: hl-portainer
        status: true

      - title: Sonarr
        url: https://sonarr.tbrouwer.com
        icon: hl-sonarr
        status: true

      - title: Radarr
        url: https://radarr.tbrouwer.com
        icon: hl-radarr
        status: true

      - title: Bazarr
        url: https://bazarr.tbrouwer.com
        icon: hl-bazarr
        status: true

      - title: Readarr
        url: https://readarr.tbrouwer.com
        icon: hl-readarr
        status: true

      - title: Prowlarr
        url: https://prowlarr.tbrouwer.com
        icon: hl-prowlarr
        status: true

      - title: FlareSolverr
        url: http://10.12.12.106:8191
        icon: hl-flaresolverr
        status: true

      - title: qBittorrent
        url: https://torrent.tbrouwer.com
        icon: hl-qbittorrent
        status: true

      - title: Traefik
        url: http://10.12.12.115:8080
        icon: hl-traefik
        status: true

      - title: Proxmox Backup
        url: https://pve-backup.tbrouwer.com
        icon: hl-proxmox
        status: true

      - title: Router
        url: http://10.12.12.1/
        icon: hl-asus-router
        status: true

  - title: secondary
    links:
      - title: Google Calendar
        url: https://calendar.google.com
        icon: hl-google-calendar

      - title: Portfolio
        url: https://www.tbrouwer.com
        icon: fas-globe
        status: true

      - title: Youtube
        url: https://www.youtube.com
        icon: hl-youtube

      - title: Netflix
        url: https://www.netflix.com
        icon: hl-netflix

      - title: Jellyfin
        url: https://jellyfin.tbrouwer.com
        icon: hl-jellyfin
        status: true

      - title: Spotify
        url: https://open.spotify.com
        icon: hl-spotify

      - title: Home Assistant
        url: https://ha.tbrouwer.com
        icon: hl-home-assistant
        status: true

      - title: Tandoor
        url: https://tandoor.tbrouwer.com
        icon: hl-tandoor-recipes
        status: true

      - title: iCloud
        url: https://www.icloud.com
        icon: favicon

      - title: Reddit
        url: https://www.reddit.com/
        icon: hl-reddit

      - title: Linkedin
        url: https://www.linkedin.com/in/tycho-brouwer-6306ba274
        icon: hl-linkedin

      - title: IMDB
        url: https://www.imdb.com/
        icon: favicon

      - title: PayPal
        url: https://www.paypal.com/myaccount/summary
        icon: hl-paypal
