title: "Dashboard"

layout:
  sections: 4
  width: 2
  sectionPadding: 20
  cardPadding: 10

style:
  background: "#181926"
  sectionBackground: "#24273a"
  cardBackground: "#181926"
  cardHover: "#c6a0f6"
  text: "#cad3f5"
  textHover: "#24273a"
  configaccent: "#c6a0f6"

linkSections:
  - title: "main"
    links:
      - title: "Proxmox"
        link: "https://pve.tbrouwer.com"
        icon: "hl-proxmox"
      - title: "Passbolt"
        link: "https://passbolt.tbrouwer.com"
        icon: "hl-passbolt"
      - title: "Grafana"
        link: "https://grafana.tbrouwer.com"
        icon: "hl-grafana"
      - title: "Pi-hole"
        link: "https://pihole.tbrouwer.com"
        icon: "hl-pi-hole"
      - title: "Pi-hole 2"
        link: "https://pihole-2.tbrouwer.com"
        icon: "hl-pi-hole"
      - title: "Wireguard"
        link: "https://wireguard.tbrouwer.com"
        icon: "hl-wireguard"
      - title: "Portainer"
        link: "https://portainer.tbrouwer.com"
        icon: "hl-portainer"
      - title: "Sonarr"
        link: "https://sonarr.tbrouwer.com"
        icon: "hl-sonarr"
      - title: "Radarr"
        link: "https://radarr.tbrouwer.com"
        icon: "hl-radarr"
      - title: "Bazarr"
        link: "https://bazarr.tbrouwer.com"
        icon: "hl-bazarr"
      - title: "Readarr"
        link: "https://readarr.tbrouwer.com"
        icon: "hl-readarr"
      - title: "Prowlarr"
        link: "https://prowlarr.tbrouwer.com"
        icon: "hl-prowlarr"
      - title: "FlareSolverr"
        link: "https://flaresolverr.tbrouwer.com"
        icon: "hl-flaresolverr"
      - title: "qBittorrent"
        link: "https://qbittorrent.tbrouwer.com"
        icon: "hl-qbittorrent"
      - title: "Traefik"
        link: "http://portainer.home:8080"
        icon: "hl-traefik"
      - title: "InfluxDB"
        link: "https://influxDB.tbrouwer.com"
        icon: "hl-influxdb"
      - title: "Proxmox Backup"
        link: "https://pve-backup.tbrouwer.com"
        icon: "hl-proxmox"
      - title: "Router"
        link: "http://10.12.12.1/"
        icon: "hl-asus-router"

  - title: "secondary"
    links:
      - title: "Google Calendar"
        link: "https://calendar.google.com"
        icon: "hl-google-calendar"
      - title: "Portfolio"
        link: "https://www.tbrouwer.com"
        icon: "fas-globe"
      - title: "Youtube"
        link: "https://www.youtube.com"
        icon: "hl-youtube"
      - title: "Netflix"
        link: "https://www.netflix.com"
        icon: "hl-netflix"
      - title: "Jellyfin"
        link: "https://jellyfin.tbrouwer.com"
        icon: "hl-jellyfin"
      - title: "Spotify"
        link: "https://open.spotify.com"
        icon: "hl-spotify"
      - title: "Home Assistant"
        link: "https://ha.tbrouwer.com"
        icon: "hl-home-assistant"
      - title: "Tandoor"
        link: "https://tandoor.tbrouwer.com"
        icon: "hl-tandoor-recipes"
      - title: "iCloud"
        link: "https://www.icloud.com"
        icon: ""
