layout:
  sections: 4
  width: 2

style:
  accentColor: "#4da6ff" 

linkSections:
  - title: "main"
    links:
      - title: "portfolio"
        link: "https://tbrouwer.com"
        icon: "fas-globe"
      - title: "google"
        link: "https://google.com"
        icon: ""
  - title: "secondary"
    links:
      - title: "portfolio 2"
        link: "https://tbrouwer.com"
        icon: ""
      - title: "google 2"
        link: "https://google.com"
        icon: ""
